pipelines:
  branches:
    main:
      - step:
          name: "Main Branch Deployment"
          deployment: Production
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $SSH_USER
                PORT: $PORT
                SERVER: 5.161.213.123
                COMMAND: '/home/neetu/quizeepay_web.sh'
